# Generated by Django 6.0.3 on 2026-06-30 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foxieterest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='liked_by',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
